<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'FluxMedia\\Symfony\\Polyfill\\Php80\\' => array($vendorDir . '/symfony/polyfill-php80'),
    'FluxMedia\\Symfony\\Polyfill\\Mbstring\\' => array($vendorDir . '/symfony/polyfill-mbstring'),
    'FluxMedia\\Symfony\\Polyfill\\Ctype\\' => array($vendorDir . '/symfony/polyfill-ctype'),
    'FluxMedia\\Symfony\\Contracts\\Service\\' => array($vendorDir . '/symfony/service-contracts'),
    'FluxMedia\\Symfony\\Contracts\\Cache\\' => array($vendorDir . '/symfony/cache-contracts'),
    'FluxMedia\\Symfony\\Component\\VarExporter\\' => array($vendorDir . '/symfony/var-exporter'),
    'FluxMedia\\Symfony\\Component\\Process\\' => array($vendorDir . '/symfony/process'),
    'FluxMedia\\Symfony\\Component\\Filesystem\\' => array($vendorDir . '/symfony/filesystem'),
    'FluxMedia\\Symfony\\Component\\Cache\\' => array($vendorDir . '/symfony/cache'),
    'FluxMedia\\Psr\\Log\\' => array($vendorDir . '/psr/log/Psr/Log'),
    'FluxMedia\\Psr\\Container\\' => array($vendorDir . '/psr/container/src'),
    'FluxMedia\\Psr\\Cache\\' => array($vendorDir . '/psr/cache/src'),
    'FluxMedia\\FluxPlugins\\Common\\' => array($vendorDir . '/stratease/flux-plugins-common/src'),
    'FluxMedia\\Evenement\\' => array($vendorDir . '/evenement/evenement/src'),
);
