<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'Neutron' => array($vendorDir . '/neutron/temporary-filesystem/src'),
    'FluxMedia\\FFMpeg' => array($vendorDir . '/php-ffmpeg/php-ffmpeg/src'),
    'Alchemy' => array($vendorDir . '/alchemy/binary-driver/src'),
);
