name: CI

on:
  push:
    paths:
      - "newspack-bedrock/**"
      - "newswoo/**"
      - ".github/workflows/ci.yml"
  pull_request:
    paths:
      - "newspack-bedrock/**"
      - "newswoo/**"
      - ".github/workflows/ci.yml"

jobs:
  newspack-bedrock:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: newspack-bedrock
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          extensions: zip, mbstring
          coverage: none
      - name: Validate composer.json
        run: composer validate --no-check-publish
      - name: Install
        run: composer install --no-interaction --prefer-dist
      - name: Tests
        run: composer test

  newswoo:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: newswoo
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          extensions: zip, mbstring
          coverage: none
      - name: Validate composer.json
        run: composer validate --no-check-publish
      - name: Install
        run: composer install --no-interaction --prefer-dist
      - name: Tests
        run: composer test

